### PR TITLE
Append the item "Required" to README.md.

### PR DESCRIPTION
**Pull request by Yukiho-YOSHIEDA**
Added these.
* Required Python version
* Required libraries
  * pykakasi

### CODE REVIEW

**Comment by get-me-power** [comment]
@Yukiho-YOSHIEDA 

Hmm. Prease change it bit like this.

```
[pykakasi](https://github.com/miurahr/pykakasi)
```

**Comment by get-me-power** [comment]
@Yukiho-YOSHIEDA 

Thanks. Please squash commit.
If you do squash, I will merge.

**Comment by Yukiho-YOSHIEDA** [comment]
@kazukazuinaina 
Done it!

**Comment by get-me-power** [comment]
Thanks!

**Pull request merged**
